spring.application.name=BusRouteAPI

management.endpoints.web.exposure.include=*
spring.jpa.defer-datasource-initialization=true

spring.security.oauth2.client.registration.google.client-id=876726623802-196jfsuqn1bld474s6qiu67ffphpjvkd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tamangom818@gmail.com
spring.mail.password=fxcyzrpnlygvpsxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.open-in-view=true

server.address=0.0.0.0
server.port=8080
 
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

frontend.url=${FRONTEND_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.busroute.api=DEBUG

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.active=default

